add_newline = false
# A minimal left prompt
format = """$directory$character"""
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[os]
format = "on [($symbol )]($style)"
style = "bold blue"
disabled = false

[character]
vicmd_symbol = "[N] >>>"
success_symbol = "[ðŸ•‰  ](bold purple)[:](bold green)"

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'
